apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjR2hoYVhwMWJHeHBianBoYVc1MWNtdHBiamczIiAgICAKCQl9Cgl9LAoJImNyZWRIZWxwZXJzIjogewoJCSJhc2lhLmdjci5pbyI6ICJnY2xvdWQiLAoJCSJldS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkiZ2NyLmlvIjogImdjbG91ZCIsCgkJIm1hcmtldHBsYWNlLmdjci5pbyI6ICJnY2xvdWQiLAoJCSJzdGFnaW5nLWs4cy5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkidXMuZ2NyLmlvIjogImdjbG91ZCIKCX0KfQo=
type: kubernetes.io/dockerconfigjson
