apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjR2hoYVhwMWJHeHBianBuYUhCZldWZENhVGg0Vm5SMlJWbFlZV05uYWt0a1VFOXVPRE50ZG1oYVpYVkdNVlJ3UVVKQyIgICAgCgkJfQoJfSwKCSJjcmVkSGVscGVycyI6IHsKCQkiYXNpYS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkiZXUuZ2NyLmlvIjogImdjbG91ZCIsCgkJImdjci5pbyI6ICJnY2xvdWQiLAoJCSJtYXJrZXRwbGFjZS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkic3RhZ2luZy1rOHMuZ2NyLmlvIjogImdjbG91ZCIsCgkJInVzLmdjci5pbyI6ICJnY2xvdWQiCgl9Cn0K
type: kubernetes.io/dockerconfigjson
